name: react app test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: list files
        run: ls -la
