name: react app test

on:
  workflow_dispatch:
  push:

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: list files
        run: ls -la
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test      
  deploy:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying...."
  env_variables:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: list env env_variables
        run: printenv
      

